# Generated by Django 5.0.14 on 2026-10-04 10:21

import django.core.validators
import django.db.models.deletion
import receipts.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(help_text='Номер фискального накопителя, 16 цифр', max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'ФН должен состоять ровно из 16 цифр.')], verbose_name='ФН')),
                ('fd', models.PositiveBigIntegerField(help_text='Номер фискального документа, до 10 цифр', validators=[django.core.validators.MinValueValidator(1, 'ФД должен быть положительным числом.'), django.core.validators.MaxValueValidator(9999999999, 'ФД не может быть длиннее 10 цифр.')], verbose_name='ФД')),
                ('fp', models.CharField(help_text='Фискальный признак, 10 цифр', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'ФП должен состоять ровно из 10 цифр.')], verbose_name='ФП')),
                ('purchased_at', models.DateTimeField(validators=[receipts.models.validate_purchase_date], verbose_name='Дата и время покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1000'), 'Сумма чека должна быть не меньше %(limit_value)s ₽.')], verbose_name='Сумма, ₽')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=16, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'чек',
                'verbose_name_plural': 'чеки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='unique_receipt_fn_fd_fp', violation_error_message='Этот чек уже зарегистрирован: чек с такими ФН, ФД и ФП уже есть в системе.'),
        ),
    ]
