# Generated by Django 5.0.14 on 2026-10-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('won', 'Вы выиграли'), ('processed', 'Обработан'), ('rejected', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
